type: object
required:
  - name
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
    minLength: 1
    pattern: "^[a-zA-Z0-9- ]+$"
  emails:
    type: array
    items:
      type: string
      format: email
  importFlowIds:
    type: array
    items:
      type: integer
      format: int64
  transformIds:
    type: array
    items:
      type: integer
      format: int64
  sinkIds:
    type: array
    items:
      type: integer
      format: int64
  successImportFlowId:
    type: integer
    format: int64
    default: null
  successTransformId:
    type: integer
    format: int64
    default: null
  successSinkId:
    type: integer
    format: int64
    default: -1
