get:
  summary: Returns all source instances
  operationId: findSources
  tags: ["NOT IMPLEMENTED YET", "Sources"]
  responses:
    default:
      description: Returns the matching source instances
      schema:
        type: array
        items:
          $ref: "../api.yaml#/definitions/source"
      headers:
        last-modified:
          type: string
          description: The date/time that a source was last modified

delete:
  summary: Deletes all sources
  operationId: deleteSources
  tags: ["NOT IMPLEMENTED YET", "Sources"]
  responses:
    default:
      description: Returns the sources that were deleted
      schema:
        type: array
        items:
          $ref: "../api.yaml#/definitions/source"

post:
  summary: Creates a new source
  operationId: addSource
  tags: ["Sources"]
  parameters:
    - name: source
      in: body
      description: The source to add
      required: true
      schema:
        $ref: "../api.yaml#/definitions/source"
  responses:
    201:
      description: Returns the newly-added source
      schema:
        $ref: "../api.yaml#/definitions/source"
      headers:
        Location:
          type: string
          description: The URL of the newly-added source
