parameters:
  - $ref: "../api.yaml#/parameters/workflowId"

get:
  summary: Returns a workflow by id
  operationId: findWorkflowById
  tags: ["Workflows"]
  responses:
    default:
      description: Returns the workflow data
      schema:
        $ref: "../api.yaml#/definitions/workflow"
      headers:
        last-modified:
          type: string
          description: The date/time that the workflow was last modified

delete:
  summary: Deletes a single workflow based on the id supplied
  operationId: deleteWorkflow
  tags: ["Workflows"]
  responses:
    default:
      description: Returns the workflow that was deleted
      schema:
        $ref: "../api.yaml#/definitions/workflow"

put:
  summary: Updates a workflow by id
  tags: ["Workflows"]
  parameters:
    - name: label
      in: body
      description: The updated workflow info
      required: true
      schema:
        $ref: "../api.yaml#/definitions/workflow"
  responses:
    default:
      description: Returns the updated workflow data
      schema:
        $ref: "../api.yaml#/definitions/workflow"
